dist: trusty
language: python
sudo: true
addons:
  apt:
    packages:
      - oracle-java8-set-default
python:
  - "3.4"
  - "3.5"
  - "3.6"
env:
  - NEO4J="3.1"
install:
  - 
  - pip install -U setuptools
  - pip install -U pip
  - pip install -U wheel
  - pip install -U tox
before_script:
  - echo 'waiting for neo4j is up'; while ! curl --output /dev/null --silent --head --fail http://127.0.0.1:7474; do sleep 1; echo -n '.'; done
script:
  - export TOXENV=py`python -c 'import sys; print("".join(map(str, sys.version_info[:2])))'`
  - echo "$TOXENV"

  - tox
cache:
  directories:
    - $HOME/.cache/pip
notifications:
  email: false
