language: python
sudo: required
services:
  - docker
python:
  - "3.5"
  - "3.6"
install:
  - pip install -U setuptools
  - pip install -U pip
  - pip install -U wheel
  - pip install -r requirements.txt
  - pip install codecov

script:
  - flake8 --show-source aioneo4j
  - isort --check-only -rc aioneo4j --diff

  - flake8 --show-source setup.py
  - isort --check-only setup.py --diff

  - flake8 --show-source tests
  - isort --check-only -rc tests --diff
  - pytest tests

after_success:
  - codecov

cache: pip
