dist: trusty
language: python
sudo: true
addons:
  apt:
    packages:
      - oracle-java8-set-default
python:
  - "3.4"
  - "3.5"
  - "3.6"
env:
  - NEO4J="3.0.0"
  - NEO4J="3.1.0"
  - NEO4J="3.2.0"
install:
  - wget -O - https://debian.neo4j.org/neotechnology.gpg.key | sudo apt-key add -
  - echo 'deb http://debian.neo4j.org/repo stable/' | sudo tee -a /etc/apt/sources.list.d/neo4j.list
  - sudo apt-get update
  - sudo apt-get install neo4j-enterprise=$NEO4J
  - sudo service neo4j start
  - pip install -U setuptools
  - pip install -U pip
  - pip install -U wheel
  - pip install -U tox
before_script:
  - "echo 'waiting for neo4j is up'; while ! curl -H \"Content-Type: application/json\" -X POST -d '{\"password\": \"neo4jneo4j\"}' http://neo4j:neo4j@127.0.0.1:7474/user/neo4j/password; do sleep 10; echo -n '.'; done"

script:
  - export TOXENV=py`python -c 'import sys; print("".join(map(str, sys.version_info[:2])))'`
  - echo "$TOXENV"

  - tox
cache:
  directories:
    - $HOME/.cache/pip
notifications:
  email: false
